/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ApplePayPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplePayPaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplePayPayment
        //private ApplePayPayment instance;

        public ApplePayPaymentTests()
        {
            // TODO uncomment below to create an instance of ApplePayPayment
            //instance = new ApplePayPayment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplePayPayment
        /// </summary>
        [Fact]
        public void ApplePayPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplePayPayment
            //Assert.IsType<ApplePayPayment>(instance);
        }

        /// <summary>
        /// Test the property 'ApplePaymentDetails'
        /// </summary>
        [Fact]
        public void ApplePaymentDetailsTest()
        {
            // TODO unit test for the property 'ApplePaymentDetails'
        }
    }
}
