/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MergeMultiDocParamsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MergeMultiDocParamsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MergeMultiDocParamsRequest
        //private MergeMultiDocParamsRequest instance;

        public MergeMultiDocParamsRequestTests()
        {
            // TODO uncomment below to create an instance of MergeMultiDocParamsRequest
            //instance = new MergeMultiDocParamsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MergeMultiDocParamsRequest
        /// </summary>
        [Fact]
        public void MergeMultiDocParamsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MergeMultiDocParamsRequest
            //Assert.IsType<MergeMultiDocParamsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DocumentsToMerge'
        /// </summary>
        [Fact]
        public void DocumentsToMergeTest()
        {
            // TODO unit test for the property 'DocumentsToMerge'
        }

        /// <summary>
        /// Test the property 'RecipientAddressSource'
        /// </summary>
        [Fact]
        public void RecipientAddressSourceTest()
        {
            // TODO unit test for the property 'RecipientAddressSource'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
