/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MultiPdfWithCaptureParamsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiPdfWithCaptureParamsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiPdfWithCaptureParamsRequest
        //private MultiPdfWithCaptureParamsRequest instance;

        public MultiPdfWithCaptureParamsRequestTests()
        {
            // TODO uncomment below to create an instance of MultiPdfWithCaptureParamsRequest
            //instance = new MultiPdfWithCaptureParamsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiPdfWithCaptureParamsRequest
        /// </summary>
        [Fact]
        public void MultiPdfWithCaptureParamsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultiPdfWithCaptureParamsRequest
            //Assert.IsType<MultiPdfWithCaptureParamsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AddressCapturePdfs'
        /// </summary>
        [Fact]
        public void AddressCapturePdfsTest()
        {
            // TODO unit test for the property 'AddressCapturePdfs'
        }

        /// <summary>
        /// Test the property 'JobTemplate'
        /// </summary>
        [Fact]
        public void JobTemplateTest()
        {
            // TODO unit test for the property 'JobTemplate'
        }

        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
