/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing PageRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageRangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PageRange
        //private PageRange instance;

        public PageRangeTests()
        {
            // TODO uncomment below to create an instance of PageRange
            //instance = new PageRange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PageRange
        /// </summary>
        [Fact]
        public void PageRangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PageRange
            //Assert.IsType<PageRange>(instance);
        }

        /// <summary>
        /// Test the property 'StartPage'
        /// </summary>
        [Fact]
        public void StartPageTest()
        {
            // TODO unit test for the property 'StartPage'
        }

        /// <summary>
        /// Test the property 'EndPage'
        /// </summary>
        [Fact]
        public void EndPageTest()
        {
            // TODO unit test for the property 'EndPage'
        }
    }
}
