/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SplitPdfParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SplitPdfParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SplitPdfParams
        //private SplitPdfParams instance;

        public SplitPdfParamsTests()
        {
            // TODO uncomment below to create an instance of SplitPdfParams
            //instance = new SplitPdfParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SplitPdfParams
        /// </summary>
        [Fact]
        public void SplitPdfParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SplitPdfParams
            //Assert.IsType<SplitPdfParams>(instance);
        }

        /// <summary>
        /// Test the property 'DocumentSourceIdentifier'
        /// </summary>
        [Fact]
        public void DocumentSourceIdentifierTest()
        {
            // TODO unit test for the property 'DocumentSourceIdentifier'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
