# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.split_pdf_with_capture_params_request import SplitPdfWithCaptureParamsRequest

class TestSplitPdfWithCaptureParamsRequest(unittest.TestCase):
    """SplitPdfWithCaptureParamsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SplitPdfWithCaptureParamsRequest:
        """Test SplitPdfWithCaptureParamsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SplitPdfWithCaptureParamsRequest`
        """
        model = SplitPdfWithCaptureParamsRequest()
        if include_optional:
            return SplitPdfWithCaptureParamsRequest(
                document_source_identifier = None,
                embedded_extraction_specs = [
                    c2m_api.models.extraction_spec.extractionSpec(
                        start_page = 56, 
                        end_page = 56, 
                        address_region = c2m_api.models.address_region.addressRegion(
                            x = 1.337, 
                            y = 1.337, 
                            width = 1.337, 
                            height = 1.337, 
                            page_offset = 56, ), )
                    ],
                payment_details = None,
                tags = [
                    ''
                    ]
            )
        else:
            return SplitPdfWithCaptureParamsRequest(
                document_source_identifier = None,
                embedded_extraction_specs = [
                    c2m_api.models.extraction_spec.extractionSpec(
                        start_page = 56, 
                        end_page = 56, 
                        address_region = c2m_api.models.address_region.addressRegion(
                            x = 1.337, 
                            y = 1.337, 
                            width = 1.337, 
                            height = 1.337, 
                            page_offset = 56, ), )
                    ],
        )
        """

    def testSplitPdfWithCaptureParamsRequest(self):
        """Test SplitPdfWithCaptureParamsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
