# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.digit import Digit

class TestDigit(unittest.TestCase):
    """Digit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDigit(self):
        """Test Digit"""
        # inst = Digit()

if __name__ == '__main__':
    unittest.main()
