# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.document_class import DocumentClass

class TestDocumentClass(unittest.TestCase):
    """DocumentClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentClass(self):
        """Test DocumentClass"""
        # inst = DocumentClass()

if __name__ == '__main__':
    unittest.main()
