# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.document_source_identifier import DocumentSourceIdentifier

class TestDocumentSourceIdentifier(unittest.TestCase):
    """DocumentSourceIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentSourceIdentifier:
        """Test DocumentSourceIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentSourceIdentifier`
        """
        model = DocumentSourceIdentifier()
        if include_optional:
            return DocumentSourceIdentifier(
                upload_request_id = 56,
                document_name = '',
                zip_id = 56
            )
        else:
            return DocumentSourceIdentifier(
                upload_request_id = 56,
                document_name = '',
                zip_id = 56,
        )
        """

    def testDocumentSourceIdentifier(self):
        """Test DocumentSourceIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
