/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplePayPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplePayPayment{}

// ApplePayPayment struct for ApplePayPayment
type ApplePayPayment struct {
	ApplePaymentDetails map[string]interface{} `json:"applePaymentDetails"`
}

type _ApplePayPayment ApplePayPayment

// NewApplePayPayment instantiates a new ApplePayPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplePayPayment(applePaymentDetails map[string]interface{}) *ApplePayPayment {
	this := ApplePayPayment{}
	this.ApplePaymentDetails = applePaymentDetails
	return &this
}

// NewApplePayPaymentWithDefaults instantiates a new ApplePayPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplePayPaymentWithDefaults() *ApplePayPayment {
	this := ApplePayPayment{}
	return &this
}

// GetApplePaymentDetails returns the ApplePaymentDetails field value
func (o *ApplePayPayment) GetApplePaymentDetails() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ApplePaymentDetails
}

// GetApplePaymentDetailsOk returns a tuple with the ApplePaymentDetails field value
// and a boolean to check if the value has been set.
func (o *ApplePayPayment) GetApplePaymentDetailsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ApplePaymentDetails, true
}

// SetApplePaymentDetails sets field value
func (o *ApplePayPayment) SetApplePaymentDetails(v map[string]interface{}) {
	o.ApplePaymentDetails = v
}

func (o ApplePayPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplePayPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applePaymentDetails"] = o.ApplePaymentDetails
	return toSerialize, nil
}

func (o *ApplePayPayment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applePaymentDetails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplePayPayment := _ApplePayPayment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplePayPayment)

	if err != nil {
		return err
	}

	*o = ApplePayPayment(varApplePayPayment)

	return err
}

type NullableApplePayPayment struct {
	value *ApplePayPayment
	isSet bool
}

func (v NullableApplePayPayment) Get() *ApplePayPayment {
	return v.value
}

func (v *NullableApplePayPayment) Set(val *ApplePayPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableApplePayPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableApplePayPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplePayPayment(val *ApplePayPayment) *NullableApplePayPayment {
	return &NullableApplePayPayment{value: val, isSet: true}
}

func (v NullableApplePayPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplePayPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


