/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MergeMultiDocParamsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergeMultiDocParamsRequest{}

// MergeMultiDocParamsRequest struct for MergeMultiDocParamsRequest
type MergeMultiDocParamsRequest struct {
	DocumentsToMerge []DocumentSourceIdentifier `json:"documentsToMerge"`
	RecipientAddressSource RecipientAddressSource `json:"recipientAddressSource"`
	Tags []string `json:"tags,omitempty"`
}

type _MergeMultiDocParamsRequest MergeMultiDocParamsRequest

// NewMergeMultiDocParamsRequest instantiates a new MergeMultiDocParamsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergeMultiDocParamsRequest(documentsToMerge []DocumentSourceIdentifier, recipientAddressSource RecipientAddressSource) *MergeMultiDocParamsRequest {
	this := MergeMultiDocParamsRequest{}
	this.DocumentsToMerge = documentsToMerge
	this.RecipientAddressSource = recipientAddressSource
	return &this
}

// NewMergeMultiDocParamsRequestWithDefaults instantiates a new MergeMultiDocParamsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergeMultiDocParamsRequestWithDefaults() *MergeMultiDocParamsRequest {
	this := MergeMultiDocParamsRequest{}
	return &this
}

// GetDocumentsToMerge returns the DocumentsToMerge field value
func (o *MergeMultiDocParamsRequest) GetDocumentsToMerge() []DocumentSourceIdentifier {
	if o == nil {
		var ret []DocumentSourceIdentifier
		return ret
	}

	return o.DocumentsToMerge
}

// GetDocumentsToMergeOk returns a tuple with the DocumentsToMerge field value
// and a boolean to check if the value has been set.
func (o *MergeMultiDocParamsRequest) GetDocumentsToMergeOk() ([]DocumentSourceIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentsToMerge, true
}

// SetDocumentsToMerge sets field value
func (o *MergeMultiDocParamsRequest) SetDocumentsToMerge(v []DocumentSourceIdentifier) {
	o.DocumentsToMerge = v
}

// GetRecipientAddressSource returns the RecipientAddressSource field value
func (o *MergeMultiDocParamsRequest) GetRecipientAddressSource() RecipientAddressSource {
	if o == nil {
		var ret RecipientAddressSource
		return ret
	}

	return o.RecipientAddressSource
}

// GetRecipientAddressSourceOk returns a tuple with the RecipientAddressSource field value
// and a boolean to check if the value has been set.
func (o *MergeMultiDocParamsRequest) GetRecipientAddressSourceOk() (*RecipientAddressSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientAddressSource, true
}

// SetRecipientAddressSource sets field value
func (o *MergeMultiDocParamsRequest) SetRecipientAddressSource(v RecipientAddressSource) {
	o.RecipientAddressSource = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MergeMultiDocParamsRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeMultiDocParamsRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MergeMultiDocParamsRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MergeMultiDocParamsRequest) SetTags(v []string) {
	o.Tags = v
}

func (o MergeMultiDocParamsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergeMultiDocParamsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["documentsToMerge"] = o.DocumentsToMerge
	toSerialize["recipientAddressSource"] = o.RecipientAddressSource
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *MergeMultiDocParamsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documentsToMerge",
		"recipientAddressSource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMergeMultiDocParamsRequest := _MergeMultiDocParamsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMergeMultiDocParamsRequest)

	if err != nil {
		return err
	}

	*o = MergeMultiDocParamsRequest(varMergeMultiDocParamsRequest)

	return err
}

type NullableMergeMultiDocParamsRequest struct {
	value *MergeMultiDocParamsRequest
	isSet bool
}

func (v NullableMergeMultiDocParamsRequest) Get() *MergeMultiDocParamsRequest {
	return v.value
}

func (v *NullableMergeMultiDocParamsRequest) Set(val *MergeMultiDocParamsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeMultiDocParamsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeMultiDocParamsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeMultiDocParamsRequest(val *MergeMultiDocParamsRequest) *NullableMergeMultiDocParamsRequest {
	return &NullableMergeMultiDocParamsRequest{value: val, isSet: true}
}

func (v NullableMergeMultiDocParamsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeMultiDocParamsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


