/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmitSingleDocWithTemplateParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitSingleDocWithTemplateParams{}

// SubmitSingleDocWithTemplateParams struct for SubmitSingleDocWithTemplateParams
type SubmitSingleDocWithTemplateParams struct {
	JobTemplate string `json:"jobTemplate"`
	PaymentDetails *PaymentDetails `json:"paymentDetails,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type _SubmitSingleDocWithTemplateParams SubmitSingleDocWithTemplateParams

// NewSubmitSingleDocWithTemplateParams instantiates a new SubmitSingleDocWithTemplateParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSingleDocWithTemplateParams(jobTemplate string) *SubmitSingleDocWithTemplateParams {
	this := SubmitSingleDocWithTemplateParams{}
	this.JobTemplate = jobTemplate
	return &this
}

// NewSubmitSingleDocWithTemplateParamsWithDefaults instantiates a new SubmitSingleDocWithTemplateParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSingleDocWithTemplateParamsWithDefaults() *SubmitSingleDocWithTemplateParams {
	this := SubmitSingleDocWithTemplateParams{}
	return &this
}

// GetJobTemplate returns the JobTemplate field value
func (o *SubmitSingleDocWithTemplateParams) GetJobTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTemplate
}

// GetJobTemplateOk returns a tuple with the JobTemplate field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParams) GetJobTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTemplate, true
}

// SetJobTemplate sets field value
func (o *SubmitSingleDocWithTemplateParams) SetJobTemplate(v string) {
	o.JobTemplate = v
}

// GetPaymentDetails returns the PaymentDetails field value if set, zero value otherwise.
func (o *SubmitSingleDocWithTemplateParams) GetPaymentDetails() PaymentDetails {
	if o == nil || IsNil(o.PaymentDetails) {
		var ret PaymentDetails
		return ret
	}
	return *o.PaymentDetails
}

// GetPaymentDetailsOk returns a tuple with the PaymentDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParams) GetPaymentDetailsOk() (*PaymentDetails, bool) {
	if o == nil || IsNil(o.PaymentDetails) {
		return nil, false
	}
	return o.PaymentDetails, true
}

// HasPaymentDetails returns a boolean if a field has been set.
func (o *SubmitSingleDocWithTemplateParams) HasPaymentDetails() bool {
	if o != nil && !IsNil(o.PaymentDetails) {
		return true
	}

	return false
}

// SetPaymentDetails gets a reference to the given PaymentDetails and assigns it to the PaymentDetails field.
func (o *SubmitSingleDocWithTemplateParams) SetPaymentDetails(v PaymentDetails) {
	o.PaymentDetails = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubmitSingleDocWithTemplateParams) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParams) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubmitSingleDocWithTemplateParams) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SubmitSingleDocWithTemplateParams) SetTags(v []string) {
	o.Tags = v
}

func (o SubmitSingleDocWithTemplateParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitSingleDocWithTemplateParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTemplate"] = o.JobTemplate
	if !IsNil(o.PaymentDetails) {
		toSerialize["paymentDetails"] = o.PaymentDetails
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *SubmitSingleDocWithTemplateParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTemplate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitSingleDocWithTemplateParams := _SubmitSingleDocWithTemplateParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitSingleDocWithTemplateParams)

	if err != nil {
		return err
	}

	*o = SubmitSingleDocWithTemplateParams(varSubmitSingleDocWithTemplateParams)

	return err
}

type NullableSubmitSingleDocWithTemplateParams struct {
	value *SubmitSingleDocWithTemplateParams
	isSet bool
}

func (v NullableSubmitSingleDocWithTemplateParams) Get() *SubmitSingleDocWithTemplateParams {
	return v.value
}

func (v *NullableSubmitSingleDocWithTemplateParams) Set(val *SubmitSingleDocWithTemplateParams) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSingleDocWithTemplateParams) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSingleDocWithTemplateParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSingleDocWithTemplateParams(val *SubmitSingleDocWithTemplateParams) *NullableSubmitSingleDocWithTemplateParams {
	return &NullableSubmitSingleDocWithTemplateParams{value: val, isSet: true}
}

func (v NullableSubmitSingleDocWithTemplateParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSingleDocWithTemplateParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


