/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentSourceIdentifierOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentSourceIdentifierOneOf1{}

// DocumentSourceIdentifierOneOf1 struct for DocumentSourceIdentifierOneOf1
type DocumentSourceIdentifierOneOf1 struct {
	UploadRequestId int32 `json:"uploadRequestId"`
	ZipId int32 `json:"zipId"`
	DocumentName string `json:"documentName"`
}

type _DocumentSourceIdentifierOneOf1 DocumentSourceIdentifierOneOf1

// NewDocumentSourceIdentifierOneOf1 instantiates a new DocumentSourceIdentifierOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentSourceIdentifierOneOf1(uploadRequestId int32, zipId int32, documentName string) *DocumentSourceIdentifierOneOf1 {
	this := DocumentSourceIdentifierOneOf1{}
	this.UploadRequestId = uploadRequestId
	this.ZipId = zipId
	this.DocumentName = documentName
	return &this
}

// NewDocumentSourceIdentifierOneOf1WithDefaults instantiates a new DocumentSourceIdentifierOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentSourceIdentifierOneOf1WithDefaults() *DocumentSourceIdentifierOneOf1 {
	this := DocumentSourceIdentifierOneOf1{}
	return &this
}

// GetUploadRequestId returns the UploadRequestId field value
func (o *DocumentSourceIdentifierOneOf1) GetUploadRequestId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UploadRequestId
}

// GetUploadRequestIdOk returns a tuple with the UploadRequestId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceIdentifierOneOf1) GetUploadRequestIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadRequestId, true
}

// SetUploadRequestId sets field value
func (o *DocumentSourceIdentifierOneOf1) SetUploadRequestId(v int32) {
	o.UploadRequestId = v
}

// GetZipId returns the ZipId field value
func (o *DocumentSourceIdentifierOneOf1) GetZipId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ZipId
}

// GetZipIdOk returns a tuple with the ZipId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceIdentifierOneOf1) GetZipIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZipId, true
}

// SetZipId sets field value
func (o *DocumentSourceIdentifierOneOf1) SetZipId(v int32) {
	o.ZipId = v
}

// GetDocumentName returns the DocumentName field value
func (o *DocumentSourceIdentifierOneOf1) GetDocumentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentName
}

// GetDocumentNameOk returns a tuple with the DocumentName field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceIdentifierOneOf1) GetDocumentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentName, true
}

// SetDocumentName sets field value
func (o *DocumentSourceIdentifierOneOf1) SetDocumentName(v string) {
	o.DocumentName = v
}

func (o DocumentSourceIdentifierOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentSourceIdentifierOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uploadRequestId"] = o.UploadRequestId
	toSerialize["zipId"] = o.ZipId
	toSerialize["documentName"] = o.DocumentName
	return toSerialize, nil
}

func (o *DocumentSourceIdentifierOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uploadRequestId",
		"zipId",
		"documentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentSourceIdentifierOneOf1 := _DocumentSourceIdentifierOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentSourceIdentifierOneOf1)

	if err != nil {
		return err
	}

	*o = DocumentSourceIdentifierOneOf1(varDocumentSourceIdentifierOneOf1)

	return err
}

type NullableDocumentSourceIdentifierOneOf1 struct {
	value *DocumentSourceIdentifierOneOf1
	isSet bool
}

func (v NullableDocumentSourceIdentifierOneOf1) Get() *DocumentSourceIdentifierOneOf1 {
	return v.value
}

func (v *NullableDocumentSourceIdentifierOneOf1) Set(val *DocumentSourceIdentifierOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSourceIdentifierOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSourceIdentifierOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSourceIdentifierOneOf1(val *DocumentSourceIdentifierOneOf1) *NullableDocumentSourceIdentifierOneOf1 {
	return &NullableDocumentSourceIdentifierOneOf1{value: val, isSet: true}
}

func (v NullableDocumentSourceIdentifierOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSourceIdentifierOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


