#!/bin/bash
# =============================================================================
# Secret Configuration Validation
# =============================================================================
# Purpose: Verify that all required secrets are properly configured
# Author: Generated by Claude
# Date: September 27, 2025
# =============================================================================

set -uo pipefail

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "🔐 Validating Secret Configuration"
echo "=================================="
echo ""

# Check local .env file
echo "1. Checking local .env file..."
if [ -f ".env" ]; then
    echo -e "${GREEN}✓${NC} .env file exists"
    
    # Source the file
    set -a
    source .env
    set +a
    
    # Check required variables
    local_ok=true
    
    if [ -n "${POSTMAN_SERRAO_API_KEY:-}" ]; then
        echo -e "${GREEN}✓${NC} POSTMAN_SERRAO_API_KEY is set (${#POSTMAN_SERRAO_API_KEY} chars)"
    else
        echo -e "${RED}✗${NC} POSTMAN_SERRAO_API_KEY is missing"
        local_ok=false
    fi
    
    if [ -n "${POSTMAN_C2M_API_KEY:-}" ]; then
        echo -e "${GREEN}✓${NC} POSTMAN_C2M_API_KEY is set (${#POSTMAN_C2M_API_KEY} chars)"
    else
        echo -e "${YELLOW}⚠${NC} POSTMAN_C2M_API_KEY is missing (optional)"
    fi
    
    if [ -n "${POSTMAN_WS:-}" ]; then
        echo -e "${GREEN}✓${NC} POSTMAN_WS is set: ${POSTMAN_WS}"
    else
        echo -e "${YELLOW}⚠${NC} POSTMAN_WS is not set (will use default)"
    fi
else
    echo -e "${RED}✗${NC} .env file missing"
    local_ok=false
fi

# Test Postman API connectivity
echo -e "\n2. Testing Postman API connectivity..."
if [ -n "${POSTMAN_SERRAO_API_KEY:-}" ]; then
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "X-Api-Key: $POSTMAN_SERRAO_API_KEY" \
        "https://api.postman.com/me")

    if [ "$response" = "200" ]; then
        echo -e "${GREEN}✓${NC} Postman API key is valid"

        # Get user info
        user_info=$(curl -s -H "X-Api-Key: $POSTMAN_SERRAO_API_KEY" \
            "https://api.postman.com/me" | jq -r '.user.username' 2>/dev/null)
        if [ -n "$user_info" ]; then
            echo -e "${BLUE}  Logged in as: $user_info${NC}"
        fi
    else
        echo -e "${RED}✗${NC} Postman API key is invalid (HTTP $response)"
    fi
else
    echo -e "${RED}✗${NC} Cannot test - API key not set"
fi

# Check workspace access
echo -e "\n3. Testing workspace access..."
workspace_id="${POSTMAN_WS}"
if [ -n "$workspace_id" ] && [ -n "${POSTMAN_SERRAO_API_KEY:-}" ]; then
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "X-Api-Key: $POSTMAN_SERRAO_API_KEY" \
        "https://api.postman.com/workspaces/$workspace_id")

    if [ "$response" = "200" ]; then
        echo -e "${GREEN}✓${NC} Workspace accessible: $workspace_id"

        # Get workspace name
        ws_name=$(curl -s -H "X-Api-Key: $POSTMAN_SERRAO_API_KEY" \
            "https://api.postman.com/workspaces/$workspace_id" | \
            jq -r '.workspace.name' 2>/dev/null)
        if [ -n "$ws_name" ] && [ "$ws_name" != "null" ]; then
            echo -e "${BLUE}  Workspace name: $ws_name${NC}"
        fi
    else
        echo -e "${RED}✗${NC} Cannot access workspace (HTTP $response)"
    fi
elif [ -z "$workspace_id" ]; then
    echo -e "${YELLOW}⚠${NC} POSTMAN_WS not set — skipping workspace check"
fi

# GitHub secrets info
echo -e "\n4. GitHub Secrets Configuration"
echo "================================"
echo "Since secrets are configured in GitHub, ensure these are set:"
echo ""
echo "Required secrets:"
echo "  • POSTMAN_SERRAO_API_KEY"
echo "  • SECURITY_REPO_TOKEN (for private repo access)"
echo ""
echo "Optional secrets:"
echo "  • POSTMAN_C2M_API_KEY"
echo "  • POSTMAN_TARGET (defaults to 'personal')"
echo ""
echo -e "${BLUE}Note: GitHub secrets cannot be validated locally${NC}"

# Summary
echo -e "\n================================"
if [ "${local_ok:-true}" = "true" ] && [ "$response" = "200" ]; then
    echo -e "${GREEN}✅ Local configuration is valid!${NC}"
    echo ""
    echo "Next steps:"
    echo "1. Push to a feature branch to test CI/CD"
    echo "2. Monitor GitHub Actions for any issues"
    echo "3. Check that artifacts are uploaded correctly"
else
    echo -e "${RED}❌ Configuration issues detected${NC}"
    echo ""
    echo "Please fix the issues above before proceeding."
fi