# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.page_range import PageRange

class TestPageRange(unittest.TestCase):
    """PageRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageRange:
        """Test PageRange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageRange`
        """
        model = PageRange()
        if include_optional:
            return PageRange(
                start_page = 56,
                end_page = 56
            )
        else:
            return PageRange(
                start_page = 56,
                end_page = 56,
        )
        """

    def testPageRange(self):
        """Test PageRange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
