# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.single_doc_job_params_request import SingleDocJobParamsRequest

class TestSingleDocJobParamsRequest(unittest.TestCase):
    """SingleDocJobParamsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleDocJobParamsRequest:
        """Test SingleDocJobParamsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleDocJobParamsRequest`
        """
        model = SingleDocJobParamsRequest()
        if include_optional:
            return SingleDocJobParamsRequest(
                document_source_identifier = None,
                recipient_address_sources = [
                    null
                    ],
                job_options = c2m_api.models.job_options.jobOptions(
                    document_class = 'businessLetter', 
                    layout = 'portrait', 
                    mailclass = 'firstClassMail', 
                    paper_type = 'letter', 
                    print_option = 'none', 
                    envelope = 'flat', ),
                payment_details = None,
                tags = [
                    ''
                    ]
            )
        else:
            return SingleDocJobParamsRequest(
                document_source_identifier = None,
                recipient_address_sources = [
                    null
                    ],
                job_options = c2m_api.models.job_options.jobOptions(
                    document_class = 'businessLetter', 
                    layout = 'portrait', 
                    mailclass = 'firstClassMail', 
                    paper_type = 'letter', 
                    print_option = 'none', 
                    envelope = 'flat', ),
        )
        """

    def testSingleDocJobParamsRequest(self):
        """Test SingleDocJobParamsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
