/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentSourceIdentifierOneOf {
    #[serde(rename = "uploadRequestId")]
    pub upload_request_id: i32,
    #[serde(rename = "documentName")]
    pub document_name: String,
}

impl DocumentSourceIdentifierOneOf {
    pub fn new(upload_request_id: i32, document_name: String) -> DocumentSourceIdentifierOneOf {
        DocumentSourceIdentifierOneOf {
            upload_request_id,
            document_name,
        }
    }
}

