/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaperType {
    #[serde(rename = "letter")]
    Letter,
    #[serde(rename = "legal")]
    Legal,
    #[serde(rename = "postcard")]
    Postcard,

}

impl std::fmt::Display for PaperType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Letter => write!(f, "letter"),
            Self::Legal => write!(f, "legal"),
            Self::Postcard => write!(f, "postcard"),
        }
    }
}

impl Default for PaperType {
    fn default() -> PaperType {
        Self::Letter
    }
}

