/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecipientAddressSource {
    ExactlyOneNewAddress(Box<models::RecipientAddress>),
    ExactlyOneListId(i32),
    ExactlyOneId(i32),
}

impl Default for RecipientAddressSource {
    fn default() -> Self {
        Self::ExactlyOneNewAddress(Default::default())
    }
}

