/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShortTokenRequest {
    /// Optional if the long-term token is provided in Authorization header
    #[serde(rename = "long_token", skip_serializing_if = "Option::is_none")]
    pub long_token: Option<String>,
    /// Optional scope narrowing; defaults to the long-term token's scopes
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl ShortTokenRequest {
    pub fn new() -> ShortTokenRequest {
        ShortTokenRequest {
            long_token: None,
            scopes: None,
        }
    }
}

