/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitSingleDocWithTemplateParams {
    #[serde(rename = "jobTemplate")]
    pub job_template: String,
    #[serde(rename = "paymentDetails", skip_serializing_if = "Option::is_none")]
    pub payment_details: Option<Box<models::PaymentDetails>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl SubmitSingleDocWithTemplateParams {
    pub fn new(job_template: String) -> SubmitSingleDocWithTemplateParams {
        SubmitSingleDocWithTemplateParams {
            job_template,
            payment_details: None,
            tags: None,
        }
    }
}

