/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param x 
 * @param y 
 * @param width 
 * @param height 
 * @param pageOffset 
 */


data class AddressRegion (

    @Json(name = "x")
    val x: java.math.BigDecimal,

    @Json(name = "y")
    val y: java.math.BigDecimal,

    @Json(name = "width")
    val width: java.math.BigDecimal,

    @Json(name = "height")
    val height: java.math.BigDecimal,

    @Json(name = "pageOffset")
    val pageOffset: kotlin.Int

) {


}

