/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code OAuth-style error code
 * @param message Human-readable error message
 * @param details Additional error details
 */


data class AuthError (

    /* OAuth-style error code */
    @Json(name = "code")
    val code: kotlin.String,

    /* Human-readable error message */
    @Json(name = "message")
    val message: kotlin.String,

    /* Additional error details */
    @Json(name = "details")
    val details: kotlin.Any? = null

) {


}

