/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: visa,mastercard,discover,americanExpress
 */

@JsonClass(generateAdapter = false)
enum class CardType(val value: kotlin.String) {

    @Json(name = "visa")
    visa("visa"),

    @Json(name = "mastercard")
    mastercard("mastercard"),

    @Json(name = "discover")
    discover("discover"),

    @Json(name = "americanExpress")
    americanExpress("americanExpress");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CardType) "$data" else null

        /**
         * Returns a valid [CardType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CardType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

