/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param zipId 
 * @param documentName 
 */


data class DocumentSourceIdentifierOneOf2 (

    @Json(name = "zipId")
    val zipId: kotlin.Int,

    @Json(name = "documentName")
    val documentName: kotlin.String

) {


}

