/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.DocumentSourceIdentifierOneOf
import com.c2m.api.models.DocumentSourceIdentifierOneOf1
import com.c2m.api.models.DocumentSourceIdentifierOneOf2

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uploadRequestId 
 * @param documentName 
 * @param zipId 
 */


data class DocumentSourceIdentifier (

    @Json(name = "uploadRequestId")
    val uploadRequestId: kotlin.Int,

    @Json(name = "documentName")
    val documentName: kotlin.String,

    @Json(name = "zipId")
    val zipId: kotlin.Int

) {


}

