/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One of several credential mechanisms must be provided.
 *
 * @param grantType The authentication grant type
 * @param clientId Client identifier issued by Click2Mail
 * @param clientSecret Required if using client_credentials with secret
 * @param otpCode Required if your policy mandates OTP for issuance
 * @param assertionType Required when grant_type=assertion
 * @param assertion Signed JWT or other accepted assertion
 * @param scopes Scopes to assign to the long-term token
 * @param ttlSeconds Requested lifetime (1 hour - 90 days). Server may clamp.
 */


data class LongTokenRequest (

    /* The authentication grant type */
    @Json(name = "grant_type")
    val grantType: LongTokenRequest.GrantType,

    /* Client identifier issued by Click2Mail */
    @Json(name = "client_id")
    val clientId: kotlin.String,

    /* Required if using client_credentials with secret */
    @Json(name = "client_secret")
    val clientSecret: kotlin.String? = null,

    /* Required if your policy mandates OTP for issuance */
    @Json(name = "otp_code")
    val otpCode: kotlin.String? = null,

    /* Required when grant_type=assertion */
    @Json(name = "assertion_type")
    val assertionType: kotlin.String? = null,

    /* Signed JWT or other accepted assertion */
    @Json(name = "assertion")
    val assertion: kotlin.String? = null,

    /* Scopes to assign to the long-term token */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>? = null,

    /* Requested lifetime (1 hour - 90 days). Server may clamp. */
    @Json(name = "ttl_seconds")
    val ttlSeconds: kotlin.Int? = null

) {

    /**
     * The authentication grant type
     *
     * Values: client_credentials,assertion
     */
    @JsonClass(generateAdapter = false)
    enum class GrantType(val value: kotlin.String) {
        @Json(name = "client_credentials") client_credentials("client_credentials"),
        @Json(name = "assertion") assertion("assertion");
    }

}

