/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tokenType 
 * @param accessToken Short-lived JWT
 * @param expiresIn Lifetime in seconds (e.g., 900 for 15 minutes)
 * @param expiresAt ISO 8601 timestamp of expiration
 * @param scopes Granted scopes
 * @param tokenId Server-issued identifier for this token
 */


data class ShortTokenResponse (

    @Json(name = "token_type")
    val tokenType: ShortTokenResponse.TokenType,

    /* Short-lived JWT */
    @Json(name = "access_token")
    val accessToken: kotlin.String,

    /* Lifetime in seconds (e.g., 900 for 15 minutes) */
    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    /* ISO 8601 timestamp of expiration */
    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    /* Granted scopes */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>? = null,

    /* Server-issued identifier for this token */
    @Json(name = "token_id")
    val tokenId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: Bearer
     */
    @JsonClass(generateAdapter = false)
    enum class TokenType(val value: kotlin.String) {
        @Json(name = "Bearer") Bearer("Bearer");
    }

}

