/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.RecipientAddressSource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param documentSourceIdentifier 
 * @param recipientAddressSource 
 */


data class SubmitMultiDocWithTemplateParamsRequestItemsInner (

    @Json(name = "documentSourceIdentifier")
    val documentSourceIdentifier: DocumentSourceIdentifier,

    @Json(name = "recipientAddressSource")
    val recipientAddressSource: RecipientAddressSource

) {


}

