//
// AchDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AchDetails: Codable, JSONEncodable, Hashable {

    public var routingNumber: String
    public var accountNumber: String
    public var checkDigit: Int

    public init(routingNumber: String, accountNumber: String, checkDigit: Int) {
        self.routingNumber = routingNumber
        self.accountNumber = accountNumber
        self.checkDigit = checkDigit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routingNumber
        case accountNumber
        case checkDigit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(routingNumber, forKey: .routingNumber)
        try container.encode(accountNumber, forKey: .accountNumber)
        try container.encode(checkDigit, forKey: .checkDigit)
    }
}

