//
// AuthError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthError: Codable, JSONEncodable, Hashable {

    /** OAuth-style error code */
    public var code: String
    /** Human-readable error message */
    public var message: String
    /** Additional error details */
    public var details: AnyCodable?

    public init(code: String, message: String, details: AnyCodable? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

