//
// CardType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CardType: String, Codable, CaseIterable {
    case visa = "visa"
    case mastercard = "mastercard"
    case discover = "discover"
    case americanexpress = "americanExpress"
}
