//
// DocumentSourceIdentifierOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DocumentSourceIdentifierOneOf1: Codable, JSONEncodable, Hashable {

    public var uploadRequestId: Int
    public var zipId: Int
    public var documentName: String

    public init(uploadRequestId: Int, zipId: Int, documentName: String) {
        self.uploadRequestId = uploadRequestId
        self.zipId = zipId
        self.documentName = documentName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uploadRequestId
        case zipId
        case documentName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uploadRequestId, forKey: .uploadRequestId)
        try container.encode(zipId, forKey: .zipId)
        try container.encode(documentName, forKey: .documentName)
    }
}

