//
// DocumentFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DocumentFormat: String, Codable, CaseIterable {
    case pdf = "pdf"
    case doc = "doc"
    case docx = "docx"
    case pub = "pub"
    case ppt = "ppt"
    case pptx = "pptx"
    case png = "png"
    case jpeg = "jpeg"
    case odt = "odt"
}
