//
// DocumentSourceIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DocumentSourceIdentifier: Codable, JSONEncodable, Hashable {
    case typeDocumentSourceIdentifierOneOf(DocumentSourceIdentifierOneOf)
    case typeDocumentSourceIdentifierOneOf1(DocumentSourceIdentifierOneOf1)
    case typeDocumentSourceIdentifierOneOf2(DocumentSourceIdentifierOneOf2)
    case typeInt(Int)
    case typeString(String)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeDocumentSourceIdentifierOneOf(let value):
            try container.encode(value)
        case .typeDocumentSourceIdentifierOneOf1(let value):
            try container.encode(value)
        case .typeDocumentSourceIdentifierOneOf2(let value):
            try container.encode(value)
        case .typeInt(let value):
            try container.encode(value)
        case .typeString(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(DocumentSourceIdentifierOneOf.self) {
            self = .typeDocumentSourceIdentifierOneOf(value)
        } else if let value = try? container.decode(DocumentSourceIdentifierOneOf1.self) {
            self = .typeDocumentSourceIdentifierOneOf1(value)
        } else if let value = try? container.decode(DocumentSourceIdentifierOneOf2.self) {
            self = .typeDocumentSourceIdentifierOneOf2(value)
        } else if let value = try? container.decode(Int.self) {
            self = .typeInt(value)
        } else if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of DocumentSourceIdentifier"))
        }
    }
}

