//
// Envelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Envelope: String, Codable, CaseIterable {
    case flat = "flat"
    case windowedflat = "windowedFlat"
    case letter = "letter"
    case legal = "legal"
    case postcard = "postcard"
}
