//
// ExtractionSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtractionSpec: Codable, JSONEncodable, Hashable {

    public var startPage: Int
    public var endPage: Int
    public var addressRegion: AddressRegion

    public init(startPage: Int, endPage: Int, addressRegion: AddressRegion) {
        self.startPage = startPage
        self.endPage = endPage
        self.addressRegion = addressRegion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startPage
        case endPage
        case addressRegion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(startPage, forKey: .startPage)
        try container.encode(endPage, forKey: .endPage)
        try container.encode(addressRegion, forKey: .addressRegion)
    }
}

