//
// InvoiceDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvoiceDetails: Codable, JSONEncodable, Hashable {

    public var invoiceNumber: String
    public var amountDue: Double

    public init(invoiceNumber: String, amountDue: Double) {
        self.invoiceNumber = invoiceNumber
        self.amountDue = amountDue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invoiceNumber
        case amountDue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invoiceNumber, forKey: .invoiceNumber)
        try container.encode(amountDue, forKey: .amountDue)
    }
}

