//
// JobOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JobOptions: Codable, JSONEncodable, Hashable {

    public var documentClass: DocumentClass
    public var layout: Layout
    public var mailclass: Mailclass
    public var paperType: PaperType
    public var printOption: PrintOption
    public var envelope: Envelope

    public init(documentClass: DocumentClass, layout: Layout, mailclass: Mailclass, paperType: PaperType, printOption: PrintOption, envelope: Envelope) {
        self.documentClass = documentClass
        self.layout = layout
        self.mailclass = mailclass
        self.paperType = paperType
        self.printOption = printOption
        self.envelope = envelope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentClass
        case layout
        case mailclass
        case paperType
        case printOption
        case envelope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(documentClass, forKey: .documentClass)
        try container.encode(layout, forKey: .layout)
        try container.encode(mailclass, forKey: .mailclass)
        try container.encode(paperType, forKey: .paperType)
        try container.encode(printOption, forKey: .printOption)
        try container.encode(envelope, forKey: .envelope)
    }
}

