//
// Mailclass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Mailclass: String, Codable, CaseIterable {
    case firstclassmail = "firstClassMail"
    case prioritymail = "priorityMail"
    case largeenvelope = "largeEnvelope"
}
