//
// MergeMultiDocParamsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MergeMultiDocParamsRequest: Codable, JSONEncodable, Hashable {

    public var documentsToMerge: [DocumentSourceIdentifier]
    public var recipientAddressSource: RecipientAddressSource
    public var tags: [String]?

    public init(documentsToMerge: [DocumentSourceIdentifier], recipientAddressSource: RecipientAddressSource, tags: [String]? = nil) {
        self.documentsToMerge = documentsToMerge
        self.recipientAddressSource = recipientAddressSource
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentsToMerge
        case recipientAddressSource
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(documentsToMerge, forKey: .documentsToMerge)
        try container.encode(recipientAddressSource, forKey: .recipientAddressSource)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

