//
// PrintOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PrintOption: String, Codable, CaseIterable {
    case _none = "none"
    case color = "color"
    case grayscale = "grayscale"
}
