//
// SplitPdfParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SplitPdfParams: Codable, JSONEncodable, Hashable {

    public var documentSourceIdentifier: DocumentSourceIdentifier
    public var items: [SplitPdfParamsRequestItemsInner]
    public var paymentDetails: PaymentDetails?
    public var tags: [String]?

    public init(documentSourceIdentifier: DocumentSourceIdentifier, items: [SplitPdfParamsRequestItemsInner], paymentDetails: PaymentDetails? = nil, tags: [String]? = nil) {
        self.documentSourceIdentifier = documentSourceIdentifier
        self.items = items
        self.paymentDetails = paymentDetails
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentSourceIdentifier
        case items
        case paymentDetails
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(documentSourceIdentifier, forKey: .documentSourceIdentifier)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(paymentDetails, forKey: .paymentDetails)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

