//
// StandardResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StandardResponse: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var message: String?
    public var jobId: String?

    public init(status: String? = nil, message: String? = nil, jobId: String? = nil) {
        self.status = status
        self.message = message
        self.jobId = jobId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case message
        case jobId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(jobId, forKey: .jobId)
    }
}

