=begin
#C2M API v2 - Auth Overlay

#API for submitting documents with various routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PrintOption
    NONE = "none".freeze
    COLOR = "color".freeze
    GRAYSCALE = "grayscale".freeze

    def self.all_vars
      @all_vars ||= [NONE, COLOR, GRAYSCALE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrintOption.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrintOption"
    end
  end
end
