/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.c2m.model.DocumentClass;
import com.c2m.model.Envelope;
import com.c2m.model.Layout;
import com.c2m.model.Mailclass;
import com.c2m.model.PaperType;
import com.c2m.model.PrintOption;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobOptions
 */
public class JobOptionsTest {
    private final JobOptions model = new JobOptions();

    /**
     * Model tests for JobOptions
     */
    @Test
    public void testJobOptions() {
        // TODO: test JobOptions
    }

    /**
     * Test the property 'documentClass'
     */
    @Test
    public void documentClassTest() {
        // TODO: test documentClass
    }

    /**
     * Test the property 'layout'
     */
    @Test
    public void layoutTest() {
        // TODO: test layout
    }

    /**
     * Test the property 'mailclass'
     */
    @Test
    public void mailclassTest() {
        // TODO: test mailclass
    }

    /**
     * Test the property 'paperType'
     */
    @Test
    public void paperTypeTest() {
        // TODO: test paperType
    }

    /**
     * Test the property 'printOption'
     */
    @Test
    public void printOptionTest() {
        // TODO: test printOption
    }

    /**
     * Test the property 'envelope'
     */
    @Test
    public void envelopeTest() {
        // TODO: test envelope
    }

}
