/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.c2m.model.DocumentSourceIdentifier;
import com.c2m.model.ExtractionSpec;
import com.c2m.model.PaymentDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SplitPdfWithCaptureParamsRequest
 */
public class SplitPdfWithCaptureParamsRequestTest {
    private final SplitPdfWithCaptureParamsRequest model = new SplitPdfWithCaptureParamsRequest();

    /**
     * Model tests for SplitPdfWithCaptureParamsRequest
     */
    @Test
    public void testSplitPdfWithCaptureParamsRequest() {
        // TODO: test SplitPdfWithCaptureParamsRequest
    }

    /**
     * Test the property 'documentSourceIdentifier'
     */
    @Test
    public void documentSourceIdentifierTest() {
        // TODO: test documentSourceIdentifier
    }

    /**
     * Test the property 'embeddedExtractionSpecs'
     */
    @Test
    public void embeddedExtractionSpecsTest() {
        // TODO: test embeddedExtractionSpecs
    }

    /**
     * Test the property 'paymentDetails'
     */
    @Test
    public void paymentDetailsTest() {
        // TODO: test paymentDetails
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
