# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DocumentFormat(str, Enum):
    """
    DocumentFormat
    """

    """
    allowed enum values
    """
    PDF = 'pdf'
    DOC = 'doc'
    DOCX = 'docx'
    PUB = 'pub'
    PPT = 'ppt'
    PPTX = 'pptx'
    PNG = 'png'
    JPEG = 'jpeg'
    ODT = 'odt'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DocumentFormat from a JSON string"""
        return cls(json.loads(json_str))


