// <auto-generated>
/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// DocumentSourceIdentifierOneOf1
    /// </summary>
    public partial class DocumentSourceIdentifierOneOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSourceIdentifierOneOf1" /> class.
        /// </summary>
        /// <param name="uploadRequestId">uploadRequestId</param>
        /// <param name="zipId">zipId</param>
        /// <param name="documentName">documentName</param>
        [JsonConstructor]
        public DocumentSourceIdentifierOneOf1(int uploadRequestId, int zipId, string documentName)
        {
            UploadRequestId = uploadRequestId;
            ZipId = zipId;
            DocumentName = documentName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets UploadRequestId
        /// </summary>
        [JsonPropertyName("uploadRequestId")]
        public int UploadRequestId { get; set; }

        /// <summary>
        /// Gets or Sets ZipId
        /// </summary>
        [JsonPropertyName("zipId")]
        public int ZipId { get; set; }

        /// <summary>
        /// Gets or Sets DocumentName
        /// </summary>
        [JsonPropertyName("documentName")]
        public string DocumentName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentSourceIdentifierOneOf1 {\n");
            sb.Append("  UploadRequestId: ").Append(UploadRequestId).Append("\n");
            sb.Append("  ZipId: ").Append(ZipId).Append("\n");
            sb.Append("  DocumentName: ").Append(DocumentName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentSourceIdentifierOneOf1" />
    /// </summary>
    public class DocumentSourceIdentifierOneOf1JsonConverter : JsonConverter<DocumentSourceIdentifierOneOf1>
    {
        /// <summary>
        /// Deserializes json to <see cref="DocumentSourceIdentifierOneOf1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocumentSourceIdentifierOneOf1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> uploadRequestId = default;
            Option<int?> zipId = default;
            Option<string?> documentName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "uploadRequestId":
                            uploadRequestId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "zipId":
                            zipId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "documentName":
                            documentName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!uploadRequestId.IsSet)
                throw new ArgumentException("Property is required for class DocumentSourceIdentifierOneOf1.", nameof(uploadRequestId));

            if (!zipId.IsSet)
                throw new ArgumentException("Property is required for class DocumentSourceIdentifierOneOf1.", nameof(zipId));

            if (!documentName.IsSet)
                throw new ArgumentException("Property is required for class DocumentSourceIdentifierOneOf1.", nameof(documentName));

            if (uploadRequestId.IsSet && uploadRequestId.Value == null)
                throw new ArgumentNullException(nameof(uploadRequestId), "Property is not nullable for class DocumentSourceIdentifierOneOf1.");

            if (zipId.IsSet && zipId.Value == null)
                throw new ArgumentNullException(nameof(zipId), "Property is not nullable for class DocumentSourceIdentifierOneOf1.");

            if (documentName.IsSet && documentName.Value == null)
                throw new ArgumentNullException(nameof(documentName), "Property is not nullable for class DocumentSourceIdentifierOneOf1.");

            return new DocumentSourceIdentifierOneOf1(uploadRequestId.Value!.Value!, zipId.Value!.Value!, documentName.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DocumentSourceIdentifierOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentSourceIdentifierOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocumentSourceIdentifierOneOf1 documentSourceIdentifierOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, documentSourceIdentifierOneOf1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocumentSourceIdentifierOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentSourceIdentifierOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocumentSourceIdentifierOneOf1 documentSourceIdentifierOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (documentSourceIdentifierOneOf1.DocumentName == null)
                throw new ArgumentNullException(nameof(documentSourceIdentifierOneOf1.DocumentName), "Property is required for class DocumentSourceIdentifierOneOf1.");

            writer.WriteNumber("uploadRequestId", documentSourceIdentifierOneOf1.UploadRequestId);

            writer.WriteNumber("zipId", documentSourceIdentifierOneOf1.ZipId);

            writer.WriteString("documentName", documentSourceIdentifierOneOf1.DocumentName);
        }
    }
}
