// <auto-generated>
/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// MergeMultiDocParams
    /// </summary>
    public partial class MergeMultiDocParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MergeMultiDocParams" /> class.
        /// </summary>
        /// <param name="documentsToMerge">documentsToMerge</param>
        /// <param name="recipientAddressSource">recipientAddressSource</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public MergeMultiDocParams(List<DocumentSourceIdentifier> documentsToMerge, RecipientAddressSource recipientAddressSource, Option<List<string>?> tags = default)
        {
            DocumentsToMerge = documentsToMerge;
            RecipientAddressSource = recipientAddressSource;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DocumentsToMerge
        /// </summary>
        [JsonPropertyName("documentsToMerge")]
        public List<DocumentSourceIdentifier> DocumentsToMerge { get; set; }

        /// <summary>
        /// Gets or Sets RecipientAddressSource
        /// </summary>
        [JsonPropertyName("recipientAddressSource")]
        public RecipientAddressSource RecipientAddressSource { get; set; }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MergeMultiDocParams {\n");
            sb.Append("  DocumentsToMerge: ").Append(DocumentsToMerge).Append("\n");
            sb.Append("  RecipientAddressSource: ").Append(RecipientAddressSource).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MergeMultiDocParams" />
    /// </summary>
    public class MergeMultiDocParamsJsonConverter : JsonConverter<MergeMultiDocParams>
    {
        /// <summary>
        /// Deserializes json to <see cref="MergeMultiDocParams" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MergeMultiDocParams Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DocumentSourceIdentifier>?> documentsToMerge = default;
            Option<RecipientAddressSource?> recipientAddressSource = default;
            Option<List<string>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "documentsToMerge":
                            documentsToMerge = new Option<List<DocumentSourceIdentifier>?>(JsonSerializer.Deserialize<List<DocumentSourceIdentifier>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "recipientAddressSource":
                            recipientAddressSource = new Option<RecipientAddressSource?>(JsonSerializer.Deserialize<RecipientAddressSource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!documentsToMerge.IsSet)
                throw new ArgumentException("Property is required for class MergeMultiDocParams.", nameof(documentsToMerge));

            if (!recipientAddressSource.IsSet)
                throw new ArgumentException("Property is required for class MergeMultiDocParams.", nameof(recipientAddressSource));

            if (documentsToMerge.IsSet && documentsToMerge.Value == null)
                throw new ArgumentNullException(nameof(documentsToMerge), "Property is not nullable for class MergeMultiDocParams.");

            if (recipientAddressSource.IsSet && recipientAddressSource.Value == null)
                throw new ArgumentNullException(nameof(recipientAddressSource), "Property is not nullable for class MergeMultiDocParams.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class MergeMultiDocParams.");

            return new MergeMultiDocParams(documentsToMerge.Value!, recipientAddressSource.Value!, tags);
        }

        /// <summary>
        /// Serializes a <see cref="MergeMultiDocParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mergeMultiDocParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MergeMultiDocParams mergeMultiDocParams, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mergeMultiDocParams, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MergeMultiDocParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mergeMultiDocParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MergeMultiDocParams mergeMultiDocParams, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mergeMultiDocParams.DocumentsToMerge == null)
                throw new ArgumentNullException(nameof(mergeMultiDocParams.DocumentsToMerge), "Property is required for class MergeMultiDocParams.");

            if (mergeMultiDocParams.RecipientAddressSource == null)
                throw new ArgumentNullException(nameof(mergeMultiDocParams.RecipientAddressSource), "Property is required for class MergeMultiDocParams.");

            if (mergeMultiDocParams.TagsOption.IsSet && mergeMultiDocParams.Tags == null)
                throw new ArgumentNullException(nameof(mergeMultiDocParams.Tags), "Property is required for class MergeMultiDocParams.");

            writer.WritePropertyName("documentsToMerge");
            JsonSerializer.Serialize(writer, mergeMultiDocParams.DocumentsToMerge, jsonSerializerOptions);
            writer.WritePropertyName("recipientAddressSource");
            JsonSerializer.Serialize(writer, mergeMultiDocParams.RecipientAddressSource, jsonSerializerOptions);
            if (mergeMultiDocParams.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, mergeMultiDocParams.Tags, jsonSerializerOptions);
            }
        }
    }
}
