// <auto-generated>
/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// SplitPdfParamsRequestItemsInner
    /// </summary>
    public partial class SplitPdfParamsRequestItemsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SplitPdfParamsRequestItemsInner" /> class.
        /// </summary>
        /// <param name="pageRange">pageRange</param>
        /// <param name="recipientAddressSources">recipientAddressSources</param>
        [JsonConstructor]
        public SplitPdfParamsRequestItemsInner(PageRange pageRange, List<RecipientAddressSource> recipientAddressSources)
        {
            PageRange = pageRange;
            RecipientAddressSources = recipientAddressSources;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets PageRange
        /// </summary>
        [JsonPropertyName("pageRange")]
        public PageRange PageRange { get; set; }

        /// <summary>
        /// Gets or Sets RecipientAddressSources
        /// </summary>
        [JsonPropertyName("recipientAddressSources")]
        public List<RecipientAddressSource> RecipientAddressSources { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SplitPdfParamsRequestItemsInner {\n");
            sb.Append("  PageRange: ").Append(PageRange).Append("\n");
            sb.Append("  RecipientAddressSources: ").Append(RecipientAddressSources).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SplitPdfParamsRequestItemsInner" />
    /// </summary>
    public class SplitPdfParamsRequestItemsInnerJsonConverter : JsonConverter<SplitPdfParamsRequestItemsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="SplitPdfParamsRequestItemsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SplitPdfParamsRequestItemsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PageRange?> pageRange = default;
            Option<List<RecipientAddressSource>?> recipientAddressSources = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pageRange":
                            pageRange = new Option<PageRange?>(JsonSerializer.Deserialize<PageRange>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "recipientAddressSources":
                            recipientAddressSources = new Option<List<RecipientAddressSource>?>(JsonSerializer.Deserialize<List<RecipientAddressSource>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!pageRange.IsSet)
                throw new ArgumentException("Property is required for class SplitPdfParamsRequestItemsInner.", nameof(pageRange));

            if (!recipientAddressSources.IsSet)
                throw new ArgumentException("Property is required for class SplitPdfParamsRequestItemsInner.", nameof(recipientAddressSources));

            if (pageRange.IsSet && pageRange.Value == null)
                throw new ArgumentNullException(nameof(pageRange), "Property is not nullable for class SplitPdfParamsRequestItemsInner.");

            if (recipientAddressSources.IsSet && recipientAddressSources.Value == null)
                throw new ArgumentNullException(nameof(recipientAddressSources), "Property is not nullable for class SplitPdfParamsRequestItemsInner.");

            return new SplitPdfParamsRequestItemsInner(pageRange.Value!, recipientAddressSources.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SplitPdfParamsRequestItemsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="splitPdfParamsRequestItemsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SplitPdfParamsRequestItemsInner splitPdfParamsRequestItemsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, splitPdfParamsRequestItemsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SplitPdfParamsRequestItemsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="splitPdfParamsRequestItemsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SplitPdfParamsRequestItemsInner splitPdfParamsRequestItemsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (splitPdfParamsRequestItemsInner.PageRange == null)
                throw new ArgumentNullException(nameof(splitPdfParamsRequestItemsInner.PageRange), "Property is required for class SplitPdfParamsRequestItemsInner.");

            if (splitPdfParamsRequestItemsInner.RecipientAddressSources == null)
                throw new ArgumentNullException(nameof(splitPdfParamsRequestItemsInner.RecipientAddressSources), "Property is required for class SplitPdfParamsRequestItemsInner.");

            writer.WritePropertyName("pageRange");
            JsonSerializer.Serialize(writer, splitPdfParamsRequestItemsInner.PageRange, jsonSerializerOptions);
            writer.WritePropertyName("recipientAddressSources");
            JsonSerializer.Serialize(writer, splitPdfParamsRequestItemsInner.RecipientAddressSources, jsonSerializerOptions);
        }
    }
}
