/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.ExpirationDate

class ExpirationDateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExpirationDate
        //val modelInstance = ExpirationDate()

        // to test the property `month`
        should("test month") {
            // uncomment below to test the property
            //modelInstance.month shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

    }
}
