/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.MergeMultiDocWithTemplateParamsRequest
import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.PaymentDetails
import com.c2m.api.models.RecipientAddressSource

class MergeMultiDocWithTemplateParamsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MergeMultiDocWithTemplateParamsRequest
        //val modelInstance = MergeMultiDocWithTemplateParamsRequest()

        // to test the property `documentsToMerge`
        should("test documentsToMerge") {
            // uncomment below to test the property
            //modelInstance.documentsToMerge shouldBe ("TODO")
        }

        // to test the property `recipientAddressSource`
        should("test recipientAddressSource") {
            // uncomment below to test the property
            //modelInstance.recipientAddressSource shouldBe ("TODO")
        }

        // to test the property `jobTemplate`
        should("test jobTemplate") {
            // uncomment below to test the property
            //modelInstance.jobTemplate shouldBe ("TODO")
        }

        // to test the property `paymentDetails`
        should("test paymentDetails") {
            // uncomment below to test the property
            //modelInstance.paymentDetails shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
