/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.SplitPdfParamsRequest
import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.PaymentDetails
import com.c2m.api.models.SplitPdfParamsRequestItemsInner

class SplitPdfParamsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SplitPdfParamsRequest
        //val modelInstance = SplitPdfParamsRequest()

        // to test the property `documentSourceIdentifier`
        should("test documentSourceIdentifier") {
            // uncomment below to test the property
            //modelInstance.documentSourceIdentifier shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `paymentDetails`
        should("test paymentDetails") {
            // uncomment below to test the property
            //modelInstance.paymentDetails shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
