/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.SubmitMultiDocWithTemplateParamsRequestItemsInner
import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.RecipientAddressSource

class SubmitMultiDocWithTemplateParamsRequestItemsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitMultiDocWithTemplateParamsRequestItemsInner
        //val modelInstance = SubmitMultiDocWithTemplateParamsRequestItemsInner()

        // to test the property `documentSourceIdentifier`
        should("test documentSourceIdentifier") {
            // uncomment below to test the property
            //modelInstance.documentSourceIdentifier shouldBe ("TODO")
        }

        // to test the property `recipientAddressSource`
        should("test recipientAddressSource") {
            // uncomment below to test the property
            //modelInstance.recipientAddressSource shouldBe ("TODO")
        }

    }
}
