=begin
#C2M API v2 - Auth Overlay

#API for submitting documents with various routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for merge_multi_doc_params
  # Operation for /jobs/multi-doc-merge
  # @param merge_multi_doc_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'merge_multi_doc_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merge_multi_doc_with_template_params
  # Operation for /jobs/multi-doc-merge-job-template
  # @param merge_multi_doc_with_template_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'merge_multi_doc_with_template_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for multi_pdf_with_capture_params
  # Operation for /jobs/multi-pdf-address-capture
  # @param multi_pdf_with_capture_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'multi_pdf_with_capture_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for single_doc_job_params
  # Operation for /jobs/single-doc
  # @param single_doc_job_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'single_doc_job_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for split_pdf_params
  # Operation for /jobs/single-pdf-split
  # @param split_pdf_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'split_pdf_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for split_pdf_with_capture_params
  # Operation for /jobs/single-pdf-split-addressCapture
  # @param split_pdf_with_capture_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'split_pdf_with_capture_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for submit_multi_doc_params
  # Operation for /jobs/multi-doc
  # @param submit_multi_doc_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'submit_multi_doc_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for submit_multi_doc_with_template_params
  # Operation for /jobs/multi-docs-job-template
  # @param submit_multi_doc_with_template_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'submit_multi_doc_with_template_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for submit_single_doc_with_template_params
  # Operation for /jobs/single-doc-job-template
  # @param submit_single_doc_with_template_params_request 
  # @param [Hash] opts the optional parameters
  # @return [StandardResponse]
  describe 'submit_single_doc_with_template_params test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
