<?php
/**
 * Digit
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace C2MApi\Model;
use \C2MApi\ObjectSerializer;

/**
 * Digit Class Doc Comment
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Digit
{
    /**
     * Possible values of this enum
     */
    public const _0 = '0';

    public const _1 = '1';

    public const _2 = '2';

    public const _3 = '3';

    public const _4 = '4';

    public const _5 = '5';

    public const _6 = '6';

    public const _7 = '7';

    public const _8 = '8';

    public const _9 = '9';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_0,
            self::_1,
            self::_2,
            self::_3,
            self::_4,
            self::_5,
            self::_6,
            self::_7,
            self::_8,
            self::_9
        ];
    }
}


