<?php
/**
 * Layout
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace C2MApi\Model;
use \C2MApi\ObjectSerializer;

/**
 * Layout Class Doc Comment
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Layout
{
    /**
     * Possible values of this enum
     */
    public const PORTRAIT = 'portrait';

    public const LANDSCAPE = 'landscape';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PORTRAIT,
            self::LANDSCAPE
        ];
    }
}


