/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddressRegion model module.
 * @module c2m_api/model/AddressRegion
 * @version 2.0.0
 */
class AddressRegion {
    /**
     * Constructs a new <code>AddressRegion</code>.
     * @alias module:c2m_api/model/AddressRegion
     * @param x {Number} 
     * @param y {Number} 
     * @param width {Number} 
     * @param height {Number} 
     * @param pageOffset {Number} 
     */
    constructor(x, y, width, height, pageOffset) { 
        
        AddressRegion.initialize(this, x, y, width, height, pageOffset);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, x, y, width, height, pageOffset) { 
        obj['x'] = x;
        obj['y'] = y;
        obj['width'] = width;
        obj['height'] = height;
        obj['pageOffset'] = pageOffset;
    }

    /**
     * Constructs a <code>AddressRegion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/AddressRegion} obj Optional instance to populate.
     * @return {module:c2m_api/model/AddressRegion} The populated <code>AddressRegion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressRegion();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('pageOffset')) {
                obj['pageOffset'] = ApiClient.convertToType(data['pageOffset'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddressRegion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddressRegion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddressRegion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AddressRegion.RequiredProperties = ["x", "y", "width", "height", "pageOffset"];

/**
 * @member {Number} x
 */
AddressRegion.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
AddressRegion.prototype['y'] = undefined;

/**
 * @member {Number} width
 */
AddressRegion.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
AddressRegion.prototype['height'] = undefined;

/**
 * @member {Number} pageOffset
 */
AddressRegion.prototype['pageOffset'] = undefined;






export default AddressRegion;

