/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentSourceIdentifier from './DocumentSourceIdentifier';

/**
 * The AddressListPdf model module.
 * @module c2m_api/model/AddressListPdf
 * @version 2.0.0
 */
class AddressListPdf {
    /**
     * Constructs a new <code>AddressListPdf</code>.
     * @alias module:c2m_api/model/AddressListPdf
     * @param documentSourceIdentifier {module:c2m_api/model/DocumentSourceIdentifier} 
     * @param addressListRegion {String} 
     */
    constructor(documentSourceIdentifier, addressListRegion) { 
        
        AddressListPdf.initialize(this, documentSourceIdentifier, addressListRegion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentSourceIdentifier, addressListRegion) { 
        obj['documentSourceIdentifier'] = documentSourceIdentifier;
        obj['addressListRegion'] = addressListRegion;
    }

    /**
     * Constructs a <code>AddressListPdf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/AddressListPdf} obj Optional instance to populate.
     * @return {module:c2m_api/model/AddressListPdf} The populated <code>AddressListPdf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressListPdf();

            if (data.hasOwnProperty('documentSourceIdentifier')) {
                obj['documentSourceIdentifier'] = DocumentSourceIdentifier.constructFromObject(data['documentSourceIdentifier']);
            }
            if (data.hasOwnProperty('addressListRegion')) {
                obj['addressListRegion'] = ApiClient.convertToType(data['addressListRegion'], 'String');
            }
            if (data.hasOwnProperty('delimiter')) {
                obj['delimiter'] = ApiClient.convertToType(data['delimiter'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddressListPdf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddressListPdf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddressListPdf.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `documentSourceIdentifier`
        if (data['documentSourceIdentifier']) { // data not null
          DocumentSourceIdentifier.validateJSON(data['documentSourceIdentifier']);
        }
        // ensure the json data is a string
        if (data['addressListRegion'] && !(typeof data['addressListRegion'] === 'string' || data['addressListRegion'] instanceof String)) {
            throw new Error("Expected the field `addressListRegion` to be a primitive type in the JSON string but got " + data['addressListRegion']);
        }
        // ensure the json data is a string
        if (data['delimiter'] && !(typeof data['delimiter'] === 'string' || data['delimiter'] instanceof String)) {
            throw new Error("Expected the field `delimiter` to be a primitive type in the JSON string but got " + data['delimiter']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

AddressListPdf.RequiredProperties = ["documentSourceIdentifier", "addressListRegion"];

/**
 * @member {module:c2m_api/model/DocumentSourceIdentifier} documentSourceIdentifier
 */
AddressListPdf.prototype['documentSourceIdentifier'] = undefined;

/**
 * @member {String} addressListRegion
 */
AddressListPdf.prototype['addressListRegion'] = undefined;

/**
 * @member {String} delimiter
 */
AddressListPdf.prototype['delimiter'] = undefined;

/**
 * @member {Array.<String>} tags
 */
AddressListPdf.prototype['tags'] = undefined;






export default AddressListPdf;

