/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DocumentFormat.
* @enum {}
* @readonly
*/
export default class DocumentFormat {
    
        /**
         * value: "pdf"
         * @const
         */
        "pdf" = "pdf";

    
        /**
         * value: "doc"
         * @const
         */
        "doc" = "doc";

    
        /**
         * value: "docx"
         * @const
         */
        "docx" = "docx";

    
        /**
         * value: "pub"
         * @const
         */
        "pub" = "pub";

    
        /**
         * value: "ppt"
         * @const
         */
        "ppt" = "ppt";

    
        /**
         * value: "pptx"
         * @const
         */
        "pptx" = "pptx";

    
        /**
         * value: "png"
         * @const
         */
        "png" = "png";

    
        /**
         * value: "jpeg"
         * @const
         */
        "jpeg" = "jpeg";

    
        /**
         * value: "odt"
         * @const
         */
        "odt" = "odt";

    

    /**
    * Returns a <code>DocumentFormat</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:c2m_api/model/DocumentFormat} The enum <code>DocumentFormat</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

