/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Layout.
* @enum {}
* @readonly
*/
export default class Layout {
    
        /**
         * value: "portrait"
         * @const
         */
        "portrait" = "portrait";

    
        /**
         * value: "landscape"
         * @const
         */
        "landscape" = "landscape";

    

    /**
    * Returns a <code>Layout</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:c2m_api/model/Layout} The enum <code>Layout</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

