/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentSourceIdentifier from './DocumentSourceIdentifier';
import PaymentDetails from './PaymentDetails';
import RecipientAddressSource from './RecipientAddressSource';

/**
 * The MergeMultiDocWithTemplateParams model module.
 * @module c2m_api/model/MergeMultiDocWithTemplateParams
 * @version 2.0.0
 */
class MergeMultiDocWithTemplateParams {
    /**
     * Constructs a new <code>MergeMultiDocWithTemplateParams</code>.
     * @alias module:c2m_api/model/MergeMultiDocWithTemplateParams
     * @param documentsToMerge {Array.<module:c2m_api/model/DocumentSourceIdentifier>} 
     * @param recipientAddressSource {module:c2m_api/model/RecipientAddressSource} 
     * @param jobTemplate {String} 
     */
    constructor(documentsToMerge, recipientAddressSource, jobTemplate) { 
        
        MergeMultiDocWithTemplateParams.initialize(this, documentsToMerge, recipientAddressSource, jobTemplate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentsToMerge, recipientAddressSource, jobTemplate) { 
        obj['documentsToMerge'] = documentsToMerge;
        obj['recipientAddressSource'] = recipientAddressSource;
        obj['jobTemplate'] = jobTemplate;
    }

    /**
     * Constructs a <code>MergeMultiDocWithTemplateParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/MergeMultiDocWithTemplateParams} obj Optional instance to populate.
     * @return {module:c2m_api/model/MergeMultiDocWithTemplateParams} The populated <code>MergeMultiDocWithTemplateParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MergeMultiDocWithTemplateParams();

            if (data.hasOwnProperty('documentsToMerge')) {
                obj['documentsToMerge'] = ApiClient.convertToType(data['documentsToMerge'], [DocumentSourceIdentifier]);
            }
            if (data.hasOwnProperty('recipientAddressSource')) {
                obj['recipientAddressSource'] = RecipientAddressSource.constructFromObject(data['recipientAddressSource']);
            }
            if (data.hasOwnProperty('jobTemplate')) {
                obj['jobTemplate'] = ApiClient.convertToType(data['jobTemplate'], 'String');
            }
            if (data.hasOwnProperty('paymentDetails')) {
                obj['paymentDetails'] = PaymentDetails.constructFromObject(data['paymentDetails']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MergeMultiDocWithTemplateParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MergeMultiDocWithTemplateParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MergeMultiDocWithTemplateParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['documentsToMerge']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['documentsToMerge'])) {
                throw new Error("Expected the field `documentsToMerge` to be an array in the JSON data but got " + data['documentsToMerge']);
            }
            // validate the optional field `documentsToMerge` (array)
            for (const item of data['documentsToMerge']) {
                DocumentSourceIdentifier.validateJSON(item);
            };
        }
        // validate the optional field `recipientAddressSource`
        if (data['recipientAddressSource']) { // data not null
          RecipientAddressSource.validateJSON(data['recipientAddressSource']);
        }
        // ensure the json data is a string
        if (data['jobTemplate'] && !(typeof data['jobTemplate'] === 'string' || data['jobTemplate'] instanceof String)) {
            throw new Error("Expected the field `jobTemplate` to be a primitive type in the JSON string but got " + data['jobTemplate']);
        }
        // validate the optional field `paymentDetails`
        if (data['paymentDetails']) { // data not null
          PaymentDetails.validateJSON(data['paymentDetails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

MergeMultiDocWithTemplateParams.RequiredProperties = ["documentsToMerge", "recipientAddressSource", "jobTemplate"];

/**
 * @member {Array.<module:c2m_api/model/DocumentSourceIdentifier>} documentsToMerge
 */
MergeMultiDocWithTemplateParams.prototype['documentsToMerge'] = undefined;

/**
 * @member {module:c2m_api/model/RecipientAddressSource} recipientAddressSource
 */
MergeMultiDocWithTemplateParams.prototype['recipientAddressSource'] = undefined;

/**
 * @member {String} jobTemplate
 */
MergeMultiDocWithTemplateParams.prototype['jobTemplate'] = undefined;

/**
 * @member {module:c2m_api/model/PaymentDetails} paymentDetails
 */
MergeMultiDocWithTemplateParams.prototype['paymentDetails'] = undefined;

/**
 * @member {Array.<String>} tags
 */
MergeMultiDocWithTemplateParams.prototype['tags'] = undefined;






export default MergeMultiDocWithTemplateParams;

