/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaperType.
* @enum {}
* @readonly
*/
export default class PaperType {
    
        /**
         * value: "letter"
         * @const
         */
        "letter" = "letter";

    
        /**
         * value: "legal"
         * @const
         */
        "legal" = "legal";

    
        /**
         * value: "postcard"
         * @const
         */
        "postcard" = "postcard";

    

    /**
    * Returns a <code>PaperType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:c2m_api/model/PaperType} The enum <code>PaperType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

