/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentSourceIdentifier from './DocumentSourceIdentifier';
import JobOptions from './JobOptions';
import PaymentDetails from './PaymentDetails';
import RecipientAddressSource from './RecipientAddressSource';

/**
 * The SingleDocJobParams model module.
 * @module c2m_api/model/SingleDocJobParams
 * @version 2.0.0
 */
class SingleDocJobParams {
    /**
     * Constructs a new <code>SingleDocJobParams</code>.
     * @alias module:c2m_api/model/SingleDocJobParams
     * @param documentSourceIdentifier {module:c2m_api/model/DocumentSourceIdentifier} 
     * @param recipientAddressSources {Array.<module:c2m_api/model/RecipientAddressSource>} 
     * @param jobOptions {module:c2m_api/model/JobOptions} 
     */
    constructor(documentSourceIdentifier, recipientAddressSources, jobOptions) { 
        
        SingleDocJobParams.initialize(this, documentSourceIdentifier, recipientAddressSources, jobOptions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentSourceIdentifier, recipientAddressSources, jobOptions) { 
        obj['documentSourceIdentifier'] = documentSourceIdentifier;
        obj['recipientAddressSources'] = recipientAddressSources;
        obj['jobOptions'] = jobOptions;
    }

    /**
     * Constructs a <code>SingleDocJobParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/SingleDocJobParams} obj Optional instance to populate.
     * @return {module:c2m_api/model/SingleDocJobParams} The populated <code>SingleDocJobParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SingleDocJobParams();

            if (data.hasOwnProperty('documentSourceIdentifier')) {
                obj['documentSourceIdentifier'] = DocumentSourceIdentifier.constructFromObject(data['documentSourceIdentifier']);
            }
            if (data.hasOwnProperty('recipientAddressSources')) {
                obj['recipientAddressSources'] = ApiClient.convertToType(data['recipientAddressSources'], [RecipientAddressSource]);
            }
            if (data.hasOwnProperty('jobOptions')) {
                obj['jobOptions'] = JobOptions.constructFromObject(data['jobOptions']);
            }
            if (data.hasOwnProperty('paymentDetails')) {
                obj['paymentDetails'] = PaymentDetails.constructFromObject(data['paymentDetails']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SingleDocJobParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SingleDocJobParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SingleDocJobParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `documentSourceIdentifier`
        if (data['documentSourceIdentifier']) { // data not null
          DocumentSourceIdentifier.validateJSON(data['documentSourceIdentifier']);
        }
        if (data['recipientAddressSources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recipientAddressSources'])) {
                throw new Error("Expected the field `recipientAddressSources` to be an array in the JSON data but got " + data['recipientAddressSources']);
            }
            // validate the optional field `recipientAddressSources` (array)
            for (const item of data['recipientAddressSources']) {
                RecipientAddressSource.validateJSON(item);
            };
        }
        // validate the optional field `jobOptions`
        if (data['jobOptions']) { // data not null
          JobOptions.validateJSON(data['jobOptions']);
        }
        // validate the optional field `paymentDetails`
        if (data['paymentDetails']) { // data not null
          PaymentDetails.validateJSON(data['paymentDetails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

SingleDocJobParams.RequiredProperties = ["documentSourceIdentifier", "recipientAddressSources", "jobOptions"];

/**
 * @member {module:c2m_api/model/DocumentSourceIdentifier} documentSourceIdentifier
 */
SingleDocJobParams.prototype['documentSourceIdentifier'] = undefined;

/**
 * @member {Array.<module:c2m_api/model/RecipientAddressSource>} recipientAddressSources
 */
SingleDocJobParams.prototype['recipientAddressSources'] = undefined;

/**
 * @member {module:c2m_api/model/JobOptions} jobOptions
 */
SingleDocJobParams.prototype['jobOptions'] = undefined;

/**
 * @member {module:c2m_api/model/PaymentDetails} paymentDetails
 */
SingleDocJobParams.prototype['paymentDetails'] = undefined;

/**
 * @member {Array.<String>} tags
 */
SingleDocJobParams.prototype['tags'] = undefined;






export default SingleDocJobParams;

