/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentSourceIdentifier from './DocumentSourceIdentifier';
import PaymentDetails from './PaymentDetails';
import SplitPdfParamsRequestItemsInner from './SplitPdfParamsRequestItemsInner';

/**
 * The SplitPdfParams model module.
 * @module c2m_api/model/SplitPdfParams
 * @version 2.0.0
 */
class SplitPdfParams {
    /**
     * Constructs a new <code>SplitPdfParams</code>.
     * @alias module:c2m_api/model/SplitPdfParams
     * @param documentSourceIdentifier {module:c2m_api/model/DocumentSourceIdentifier} 
     * @param items {Array.<module:c2m_api/model/SplitPdfParamsRequestItemsInner>} 
     */
    constructor(documentSourceIdentifier, items) { 
        
        SplitPdfParams.initialize(this, documentSourceIdentifier, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentSourceIdentifier, items) { 
        obj['documentSourceIdentifier'] = documentSourceIdentifier;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>SplitPdfParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/SplitPdfParams} obj Optional instance to populate.
     * @return {module:c2m_api/model/SplitPdfParams} The populated <code>SplitPdfParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SplitPdfParams();

            if (data.hasOwnProperty('documentSourceIdentifier')) {
                obj['documentSourceIdentifier'] = DocumentSourceIdentifier.constructFromObject(data['documentSourceIdentifier']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [SplitPdfParamsRequestItemsInner]);
            }
            if (data.hasOwnProperty('paymentDetails')) {
                obj['paymentDetails'] = PaymentDetails.constructFromObject(data['paymentDetails']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SplitPdfParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SplitPdfParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SplitPdfParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `documentSourceIdentifier`
        if (data['documentSourceIdentifier']) { // data not null
          DocumentSourceIdentifier.validateJSON(data['documentSourceIdentifier']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                SplitPdfParamsRequestItemsInner.validateJSON(item);
            };
        }
        // validate the optional field `paymentDetails`
        if (data['paymentDetails']) { // data not null
          PaymentDetails.validateJSON(data['paymentDetails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

SplitPdfParams.RequiredProperties = ["documentSourceIdentifier", "items"];

/**
 * @member {module:c2m_api/model/DocumentSourceIdentifier} documentSourceIdentifier
 */
SplitPdfParams.prototype['documentSourceIdentifier'] = undefined;

/**
 * @member {Array.<module:c2m_api/model/SplitPdfParamsRequestItemsInner>} items
 */
SplitPdfParams.prototype['items'] = undefined;

/**
 * @member {module:c2m_api/model/PaymentDetails} paymentDetails
 */
SplitPdfParams.prototype['paymentDetails'] = undefined;

/**
 * @member {Array.<String>} tags
 */
SplitPdfParams.prototype['tags'] = undefined;






export default SplitPdfParams;

