/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentDetails from './PaymentDetails';

/**
 * The SubmitSingleDocWithTemplateParams model module.
 * @module c2m_api/model/SubmitSingleDocWithTemplateParams
 * @version 2.0.0
 */
class SubmitSingleDocWithTemplateParams {
    /**
     * Constructs a new <code>SubmitSingleDocWithTemplateParams</code>.
     * @alias module:c2m_api/model/SubmitSingleDocWithTemplateParams
     * @param jobTemplate {String} 
     */
    constructor(jobTemplate) { 
        
        SubmitSingleDocWithTemplateParams.initialize(this, jobTemplate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobTemplate) { 
        obj['jobTemplate'] = jobTemplate;
    }

    /**
     * Constructs a <code>SubmitSingleDocWithTemplateParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/SubmitSingleDocWithTemplateParams} obj Optional instance to populate.
     * @return {module:c2m_api/model/SubmitSingleDocWithTemplateParams} The populated <code>SubmitSingleDocWithTemplateParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitSingleDocWithTemplateParams();

            if (data.hasOwnProperty('jobTemplate')) {
                obj['jobTemplate'] = ApiClient.convertToType(data['jobTemplate'], 'String');
            }
            if (data.hasOwnProperty('paymentDetails')) {
                obj['paymentDetails'] = PaymentDetails.constructFromObject(data['paymentDetails']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitSingleDocWithTemplateParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitSingleDocWithTemplateParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubmitSingleDocWithTemplateParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['jobTemplate'] && !(typeof data['jobTemplate'] === 'string' || data['jobTemplate'] instanceof String)) {
            throw new Error("Expected the field `jobTemplate` to be a primitive type in the JSON string but got " + data['jobTemplate']);
        }
        // validate the optional field `paymentDetails`
        if (data['paymentDetails']) { // data not null
          PaymentDetails.validateJSON(data['paymentDetails']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

SubmitSingleDocWithTemplateParams.RequiredProperties = ["jobTemplate"];

/**
 * @member {String} jobTemplate
 */
SubmitSingleDocWithTemplateParams.prototype['jobTemplate'] = undefined;

/**
 * @member {module:c2m_api/model/PaymentDetails} paymentDetails
 */
SubmitSingleDocWithTemplateParams.prototype['paymentDetails'] = undefined;

/**
 * @member {Array.<String>} tags
 */
SubmitSingleDocWithTemplateParams.prototype['tags'] = undefined;






export default SubmitSingleDocWithTemplateParams;

