=begin
#C2M API v2 - Auth Overlay

#API for submitting documents with various routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Digit
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Digit do
  let(:instance) { OpenapiClient::Digit.new }

  describe 'test an instance of Digit' do
    it 'should create an instance of Digit' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::Digit)
    end
  end

end
