/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * DocumentSourceIdentifierOneOf1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-08T10:35:42.292913-04:00[America/New_York]", comments = "Generator version: 7.15.0")
public class DocumentSourceIdentifierOneOf1 {
  public static final String SERIALIZED_NAME_UPLOAD_REQUEST_ID = "uploadRequestId";
  @SerializedName(SERIALIZED_NAME_UPLOAD_REQUEST_ID)
  @javax.annotation.Nonnull
  private Integer uploadRequestId;

  public static final String SERIALIZED_NAME_ZIP_ID = "zipId";
  @SerializedName(SERIALIZED_NAME_ZIP_ID)
  @javax.annotation.Nonnull
  private Integer zipId;

  public static final String SERIALIZED_NAME_DOCUMENT_NAME = "documentName";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_NAME)
  @javax.annotation.Nonnull
  private String documentName;

  public DocumentSourceIdentifierOneOf1() {
  }

  public DocumentSourceIdentifierOneOf1 uploadRequestId(@javax.annotation.Nonnull Integer uploadRequestId) {
    this.uploadRequestId = uploadRequestId;
    return this;
  }

  /**
   * Get uploadRequestId
   * @return uploadRequestId
   */
  @javax.annotation.Nonnull
  public Integer getUploadRequestId() {
    return uploadRequestId;
  }

  public void setUploadRequestId(@javax.annotation.Nonnull Integer uploadRequestId) {
    this.uploadRequestId = uploadRequestId;
  }


  public DocumentSourceIdentifierOneOf1 zipId(@javax.annotation.Nonnull Integer zipId) {
    this.zipId = zipId;
    return this;
  }

  /**
   * Get zipId
   * @return zipId
   */
  @javax.annotation.Nonnull
  public Integer getZipId() {
    return zipId;
  }

  public void setZipId(@javax.annotation.Nonnull Integer zipId) {
    this.zipId = zipId;
  }


  public DocumentSourceIdentifierOneOf1 documentName(@javax.annotation.Nonnull String documentName) {
    this.documentName = documentName;
    return this;
  }

  /**
   * Get documentName
   * @return documentName
   */
  @javax.annotation.Nonnull
  public String getDocumentName() {
    return documentName;
  }

  public void setDocumentName(@javax.annotation.Nonnull String documentName) {
    this.documentName = documentName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSourceIdentifierOneOf1 documentSourceIdentifierOneOf1 = (DocumentSourceIdentifierOneOf1) o;
    return Objects.equals(this.uploadRequestId, documentSourceIdentifierOneOf1.uploadRequestId) &&
        Objects.equals(this.zipId, documentSourceIdentifierOneOf1.zipId) &&
        Objects.equals(this.documentName, documentSourceIdentifierOneOf1.documentName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploadRequestId, zipId, documentName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentSourceIdentifierOneOf1 {\n");
    sb.append("    uploadRequestId: ").append(toIndentedString(uploadRequestId)).append("\n");
    sb.append("    zipId: ").append(toIndentedString(zipId)).append("\n");
    sb.append("    documentName: ").append(toIndentedString(documentName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("uploadRequestId", "zipId", "documentName"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("uploadRequestId", "zipId", "documentName"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DocumentSourceIdentifierOneOf1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DocumentSourceIdentifierOneOf1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DocumentSourceIdentifierOneOf1 is not found in the empty JSON string", DocumentSourceIdentifierOneOf1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DocumentSourceIdentifierOneOf1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DocumentSourceIdentifierOneOf1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DocumentSourceIdentifierOneOf1.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("documentName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DocumentSourceIdentifierOneOf1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DocumentSourceIdentifierOneOf1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DocumentSourceIdentifierOneOf1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DocumentSourceIdentifierOneOf1.class));

       return (TypeAdapter<T>) new TypeAdapter<DocumentSourceIdentifierOneOf1>() {
           @Override
           public void write(JsonWriter out, DocumentSourceIdentifierOneOf1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DocumentSourceIdentifierOneOf1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DocumentSourceIdentifierOneOf1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DocumentSourceIdentifierOneOf1
   * @throws IOException if the JSON string is invalid with respect to DocumentSourceIdentifierOneOf1
   */
  public static DocumentSourceIdentifierOneOf1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DocumentSourceIdentifierOneOf1.class);
  }

  /**
   * Convert an instance of DocumentSourceIdentifierOneOf1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

