/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets mailclass
 */
@JsonAdapter(Mailclass.Adapter.class)
public enum Mailclass {
  
  FIRST_CLASS_MAIL("firstClassMail"),
  
  PRIORITY_MAIL("priorityMail"),
  
  LARGE_ENVELOPE("largeEnvelope");

  private String value;

  Mailclass(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Mailclass fromValue(String value) {
    for (Mailclass b : Mailclass.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Mailclass> {
    @Override
    public void write(final JsonWriter jsonWriter, final Mailclass enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Mailclass read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Mailclass.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Mailclass.fromValue(value);
  }
}

